//Task 1
const bankAccount = {
    bankAccountID: Math.round(Math.random() * 999999), //This is to get an autogenerated ID
    accountNumber: 123456,
    credentials: ["myusername", "mypassword", 123456], //This is an array with our username, password and pin
    balance: 1000,
    createdAt: new Date().toLocaleDateString(),
    };
    
    //Task 2
    const userAccount = {
    bankAccount, //We put here the variable bankAccount. The object we just created on Task 1
    debitCard: 123456,
    firstName: "Junnel",
    lastName: "Gujol",
    birthDate: "August 27, 1986",
    validID: [
    {
    type: "Passport",
    IDNumber: 123456,
    },
    ],
    address: "Davao Del Norte",
    };
    //Task 3
    function getBankAccountDetails(username, password) {
    if (
    bankAccount.credentials[0] == username &&
    bankAccount.credentials[1] == password
    ) {
    console.log(userAccount);
    } else {
    console.log("Wrong Username or Password");
    }
    }
    function withdrawMoney(username, password, accountNumber, amount) {
    if (
    bankAccount.credentials[0] == username &&
    bankAccount.credentials[1] == password
    ) {
    if (bankAccount.accountNumber == accountNumber) {
    if (bankAccount.balance >= amount) {
    bankAccount.balance -= amount;
    console.log("You have withdrawn: " + amount);
    }
    } else {
    console.log("Wrong Account Number");
    }
    } else {
    console.log("Wrong Username or Password");
    }
    }
    function depositMoney(accountNumber, amount) {
    if (bankAccount.accountNumber == accountNumber) {
    bankAccount.accountNumber += amount;
    console.log("You deposited: " + amount);
    } else {
    console.log("Wrong Account Number");
    }
    }
    getBankAccountDetails("myusername", "mypassword");
    withdrawMoney("myusername", "mypassword", 123456, 100);
    depositMoney(123456, 5000);